services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile
    environment:
      - PYTHONPATH=/app:/app/app/backend
    ports:
      - "8080:8000"
    networks:
      - recipe-network

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile
    ports:
      - "5050:5000"
    depends_on:
      - backend
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge